### ISSUE TITLE
Грамматика

### ISSUE THREAD

**Issue by StarikTenger** [StarikTenger/RegularLanguageProblem#3]
Структуры Term/Nonterm:
* как-то хранят значение (строки или чар)
* операторы `=`, `<`

Класс грамматики:
* множество терминалов (set)
* множество нетерминалов (set)

Класс продукция:
* Левая часть - нетерминал
* Правая часть - вектор variant<Term, Nonterm>

**Comment by TonitaN** [comment]
Ну не в докере запускайте, прикрутите свой счётчик. Только инструкцию по сборке сделайте нормально.

ЗЫ - А вообще, возьмите Рефал у Терюхи и запустите руками без контейнера, проблем-то.
